name: habitbank
description: Social fitness accountability app with virtual money stakes.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: false
  assets:
    - .env
    - assets/logo.svg
    - assets/logo.png
    - assets/onboarding/1.gif
    - assets/onboarding/2.gif
    - assets/onboarding/3.gif

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/splash.png"
  ios: true
  android: true
  web: false
